name: Corrigir Autor do Exercism
on:
  push:
    branches: [ main ]

jobs:
  fix-author:
    runs-on: ubuntu-latest
    if: github.actor == 'exercism-solutions-syncer[bot]'
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Resetar Autor para o Meu Perfil
        run: |
          git config --global user.name "Martins0712"
          # COLOQUE SEU E-MAIL DO GITHUB NA LINHA ABAIXO:
          git config --global user.email "seu_email_aqui@exemplo.com"
          
          git commit --amend --reset-author --no-edit
          git push --force
