name: Corrigir Autor do Exercism
on:
  push:
    branches: [ main ]

jobs:
  fix-author:
    runs-on: ubuntu-latest
    if: github.actor != 'Martins0712'
    
    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reescrever histórico de autor
        run: |
          git config --global user.name "Martins0712"
          git config --global user.email "lucxinstex@gmail.com"
          
          git filter-branch --env-filter '
          if [ "$GIT_AUTHOR_NAME" = "exercism-solutions-syncer[bot]" ]; then
              export GIT_AUTHOR_NAME="Martins0712"
              export GIT_AUTHOR_EMAIL="lucxinstex@gmail.com"
              export GIT_COMMITTER_NAME="Martins0712"
              export GIT_COMMITTER_EMAIL="lucxinstex@gmail.com"
          fi
          ' --tag-name-filter cat -- --branches --tags

          git push --force origin main
